//! Expose all known instructions as Rust `struct`s; this is generated in
//! `build.rs`.
//!
//! See also: [`Inst`], an `enum` containing all these instructions.

// M27 Phase 5c Stage G iter 5b: no_std preludes for the generated
// assembler.rs (a 78k-line file emitted by cranelift-assembler-x64-meta).
// The generator emits `Vec<Feature>`, `vec![...]`, `.to_string()`, and
// (after meta-side patching) `alloc::borrow::Cow` / `core::fmt::Display`
// — all of which need to be in scope at the include! call site.
use alloc::string::ToString;
use alloc::vec::Vec;

use crate::Fixed;
use crate::api::{AsReg, CodeSink, RegisterVisitor, Registers, TrapCode};
use crate::gpr::{self, Gpr, Size};
use crate::imm::{Extension, Imm8, Imm16, Imm32, Imm64, Simm8, Simm32};
use crate::mem::{Amode, GprMem, XmmMem};
use crate::rex::RexPrefix;
use crate::vex::VexPrefix;
use crate::xmm::{self, Xmm};

// Include code generated by the `meta` crate.
include!(concat!(env!("OUT_DIR"), "/assembler.rs"));
