//! iwlwifi association state machine — M11 stage 4.
//!
//! Drives the scan / authenticate / associate / 4-way-handshake sequence
//! that an STA performs to join an AP.  Each state maps to a set of
//! 802.11 management frames (built in `wireless.rs`) and iwlwifi HCMDs
//! (queued via `iwlwifi_device`).
//!
//! QEMU-safe: the state machine compiles and idles in `State::Idle` when
//! no NIC is present.  On metal it is stepped by timer callbacks or
//! RX-frame interrupts.

use crate::println;
use super::{MacAddr, BCAST, build_probe_request, build_open_auth_request,
                       build_association_request};

/// Security profile for the target network.
#[derive(Copy, Clone, Debug)]
pub struct NetworkProfile {
    /// SSID bytes (up to 32).
    pub ssid: [u8; 32],
    pub ssid_len: usize,
    /// BSSID — filled in after scan finds a matching beacon/probe-resp.
    pub bssid: MacAddr,
    /// Pre-shared key (passphrase) for WPA2-Personal.
    pub psk: [u8; 64],
    pub psk_len: usize,
}

impl NetworkProfile {
    pub fn from_ssid_psk(ssid: &[u8], psk: &[u8]) -> Self {
        let mut s = [0u8; 32];
        let sl = ssid.len().min(32);
        s[..sl].copy_from_slice(&ssid[..sl]);
        let mut p = [0u8; 64];
        let pl = psk.len().min(64);
        p[..pl].copy_from_slice(&psk[..pl]);
        Self {
            ssid: s,
            ssid_len: sl,
            bssid: BCAST,
            psk: p,
            psk_len: pl,
        }
    }
}

/// Association state.
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum State {
    /// No network configured.
    Idle,
    /// Actively scanning — Probe Requests sent, waiting for Probe Responses.
    Scanning,
    /// Found target AP, sending Authentication Request (Open System, seq 1).
    Authenticating,
    /// Auth accepted, sending Association Request.
    Associating,
    /// Assoc accepted, performing WPA2 4-way handshake.
    FourWayHandshake,
    /// Keys installed, waiting for DHCP to complete.
    Dhcping,
    /// Fully connected — data frames can flow.
    Associated,
    /// Terminal failure state (wrong password, AP vanished, etc.).
    Failed,
}

/// Per-handshake nonces and counters.
#[derive(Copy, Clone, Debug)]
pub struct HandshakeState {
    /// SNonce — 32 random bytes generated by us (the STA).
    pub snonce: [u8; 32],
    /// ANonce — 32 bytes from AP's EAPOL-Key Msg1.
    pub anonce: [u8; 32],
    /// Replay counter from the current EAPOL exchange.
    pub replay: u64,
    /// MIC key (KCK) — 16 bytes derived from PTK.
    pub kck: [u8; 16],
    /// Encryption key (KEK) — 16 bytes derived from PTK.
    pub kek: [u8; 16],
    /// Temporal key (TK) — 16 bytes derived from PTK.
    pub tk: [u8; 16],
}

/// The state machine itself.
pub struct AssocStateMachine {
    pub state: State,
    pub profile: Option<NetworkProfile>,
    pub handshake: Option<HandshakeState>,
    /// Sequence number for management frames (incremented per frame).
    pub seq_num: u16,
    /// Our MAC address (filled from the NIC EEPROM during init).
    pub sta_mac: MacAddr,
    /// Retry counter — incremented on timeout, cleared on success.
    pub retries: u8,
    /// Max retries before transitioning to Failed.
    pub max_retries: u8,
}

impl AssocStateMachine {
    pub const fn new(sta_mac: MacAddr) -> Self {
        Self {
            state: State::Idle,
            profile: None,
            handshake: None,
            seq_num: 0,
            sta_mac,
            retries: 0,
            max_retries: 5,
        }
    }

    // =====================================================================
    // State entry points
    // =====================================================================

    /// Start scanning for a network.
    pub fn start_scan(&mut self, profile: NetworkProfile) {
        println!("[iwlwifi-sm] start_scan for SSID '{}'", ascii_ssid(&profile.ssid[..profile.ssid_len]));
        self.profile = Some(profile);
        self.state = State::Scanning;
        self.retries = 0;
    }

    /// Build a Probe Request frame for the current profile.
    /// Returns `(frame_bytes, length)` on success.
    pub fn build_probe_req<'a>(&mut self, out: &'a mut [u8]) -> Option<&'a [u8]> {
        let profile = self.profile.as_ref()?;
        let n = build_probe_request(out, &self.sta_mac, &profile.ssid[..profile.ssid_len])?;
        self.seq_num = self.seq_num.wrapping_add(1);
        Some(&out[..n])
    }

    /// Called when a Probe Response or Beacon is received that matches our SSID.
    /// Copies the BSSID from the frame and transitions to Authenticating.
    pub fn on_ap_found(&mut self, bssid: MacAddr) {
        if let Some(ref mut p) = self.profile {
            p.bssid = bssid;
            println!("[iwlwifi-sm] AP found  BSSID={:02X}:{:02X}:{:02X}:{:02X}:{:02X}:{:02X}",
                bssid[0], bssid[1], bssid[2], bssid[3], bssid[4], bssid[5]);
            self.state = State::Authenticating;
            self.retries = 0;
        }
    }

    /// Build an Open System Authentication Request.
    pub fn build_auth_req<'a>(&mut self, out: &'a mut [u8]) -> Option<&'a [u8]> {
        let profile = self.profile.as_ref()?;
        let n = build_open_auth_request(out, &self.sta_mac, &profile.bssid)?;
        self.seq_num = self.seq_num.wrapping_add(1);
        Some(&out[..n])
    }

    /// Called when Authentication Response (seq 2, status 0) is received.
    pub fn on_auth_accepted(&mut self) {
        println!("[iwlwifi-sm] auth accepted");
        self.state = State::Associating;
        self.retries = 0;
    }

    /// Build an Association Request.
    pub fn build_assoc_req<'a>(&mut self, out: &'a mut [u8]) -> Option<&'a [u8]> {
        let profile = self.profile.as_ref()?;
        let n = build_association_request(out, &self.sta_mac, &profile.bssid,
                                          &profile.ssid[..profile.ssid_len])?;
        self.seq_num = self.seq_num.wrapping_add(1);
        Some(&out[..n])
    }

    /// Called when Association Response (status 0) is received.
    pub fn on_assoc_accepted(&mut self) {
        println!("[iwlwifi-sm] assoc accepted — starting 4-way handshake");
        self.state = State::FourWayHandshake;
        self.retries = 0;
        // TODO(M11): generate SNonce from RNG.
        self.handshake = Some(HandshakeState {
            snonce: [0u8; 32],
            anonce: [0u8; 32],
            replay: 0,
            kck: [0u8; 16],
            kek: [0u8; 16],
            tk: [0u8; 16],
        });
    }

    /// Build EAPOL-Key Msg2 (STA → AP) in response to AP's Msg1.
    pub fn build_eapol_msg2<'a>(&mut self, out: &'a mut [u8]) -> Option<&'a [u8]> {
        let hs = self.handshake.as_mut()?;
        // TODO(M11): derive PTK from PMK + ANonce + SNonce + MACs,
        // then compute MIC over the frame with KCK.
        let n = super::build_eapol_msg2(out, &hs.snonce, hs.replay, &[])?;
        Some(&out[..n])
    }

    /// Called when EAPOL-Key Msg3 is received and MIC verifies.
    pub fn on_eapol_msg3_ok(&mut self) {
        println!("[iwlwifi-sm] EAPOL Msg3 verified — installing keys");
        self.state = State::Dhcping;
        self.retries = 0;
    }

    /// Called when DHCP completes (or we decide to use static IP).
    pub fn on_dhcp_complete(&mut self) {
        println!("[iwlwifi-sm] DHCP complete — link up");
        self.state = State::Associated;
    }

    // =====================================================================
    // Timeout / retry handling
    // =====================================================================

    /// Call this when a timer fires and the current state hasn't progressed.
    /// Returns `true` if a retry frame should be retransmitted.
    pub fn on_timeout(&mut self) -> bool {
        self.retries += 1;
        if self.retries > self.max_retries {
            println!("[iwlwifi-sm] timeout → Failed after {} retries", self.retries);
            self.state = State::Failed;
            return false;
        }
        println!("[iwlwifi-sm] retry {}/{} in state {:?}", self.retries, self.max_retries, self.state);
        true
    }

    /// Reset to Idle (e.g. on disconnect command).
    pub fn reset(&mut self) {
        self.state = State::Idle;
        self.profile = None;
        self.handshake = None;
        self.retries = 0;
    }
}

/// Helper: format SSID bytes as printable ASCII (replace non-printable with '?').
fn ascii_ssid(ssid: &[u8]) -> &str {
    // Fast path: if already ASCII, return as-is.
    if ssid.is_ascii() {
        return core::str::from_utf8(ssid).unwrap_or("???");
    }
    // Fall back to lossy display — kernel has no alloc for String.
    "(non-ascii SSID)"
}
