[package]
name = "rustc_driver"
version = "0.0.0"
edition = "2024"

[lib]
# Stage H iter 4 / Phase 5b: x86_64-unknown-none doesn't support dylib;
# semos-rustc statically links via rlib. Host can still build as rlib
# since it just re-exports rustc_driver_impl's symbols.
crate-type = ["rlib"]

[dependencies]
# tidy-alphabetical-start
rustc_driver_impl = { path = "../rustc_driver_impl" }
# tidy-alphabetical-end

[build-dependencies]
# tidy-alphabetical-start
rustc_windows_rc = { path = "../rustc_windows_rc" }
# tidy-alphabetical-end
