[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
indexmap = { version = "2.0.0", default-features = false }
rustc_hashes = { path = "../rustc_hashes" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = { version = "0.2.12", default-features = false }
# tidy-alphabetical-end

# Stage F2: PathBuf Encodable/Decodable impls need the semos-std
# path types on the SemOS target.
[target.'cfg(target_os = "none")'.dependencies]
semos-std = { path = "../../../../std-shim" }

[dev-dependencies]
# tidy-alphabetical-start
rustc_macros = { path = "../rustc_macros" }
tempfile = "3.2"
# tidy-alphabetical-end
